// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://vi24jsmaw5b7zaaso5vqypdg2y.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-x2s2mthw2bhqfic2g3g4p6v6hq"
};


export default awsmobile;
